#!/bin/sh
echo "killing jobs on c0-0 ..."
ssh c0-0 -n killall amica
echo "killing jobs on c0-1 ..."
ssh c0-1 -n killall amica
echo "killing jobs on c0-2 ..."
ssh c0-2 -n killall amica
echo "killing jobs on c0-3 ..."
ssh c0-3 -n killall amica
echo "killing jobs on c0-4 ..."
ssh c0-4 -n killall amica
echo "killing jobs on c0-5 ..."
ssh c0-5 -n killall amica
echo "killing jobs on c0-6 ..."
ssh c0-6 -n killall amica
echo "killing jobs on c0-7 ..."
ssh c0-7 -n killall amica
echo "killing jobs on c0-8 ..."
ssh c0-8 -n killall amica
echo "killing jobs on c0-9 ..."
ssh c0-9 -n killall amica
echo "killing jobs on c0-10 ..."
ssh c0-10 -n killall amica
echo "killing jobs on c0-11 ..."
ssh c0-11 -n killall amica
echo "killing jobs on c0-12 ..."
ssh c0-12 -n killall amica
echo "killing jobs on c0-13 ..."
ssh c0-13 -n killall amica
echo "killing jobs on c0-14 ..."
ssh c0-14 -n killall amica
echo "killing jobs on c0-15 ..."
ssh c0-15 -n killall amica
echo "killing jobs on c0-16 ..."
ssh c0-16 -n killall amica
echo "killing jobs on c0-17 ..."
ssh c0-17 -n killall amica
echo "killing jobs on c0-18 ..."
ssh c0-18 -n killall amica
echo "killing jobs on c0-19 ..."
ssh c0-19 -n killall amica
echo "killing jobs on c0-20 ..."
ssh c0-20 -n killall amica
