function V = nifti2spm_vol(files)

n = length(files(:,1));
V   = struct('fname', {},...
    'dim',   {},...
    'dt',    {},...
    'pinfo', {},...
    'mat',   {},...
    'n',     {},...
    'descrip', {},...
    'private',{});
V = repmat(V,n,1);
for it=1:n
    fname = deblank(files(it,:));
    V1 = load_nifti(fname);
    mat =[V1.srow_x';V1.srow_y';V1.srow_z';0 0 0 1]/[eye(4,3) [1 1 1 1]'];
    
    V(it,1)   = struct('fname', fname,...
        'dim',   V1.dim(2:4),...
        'dt',    [V1.datatype 0],...
        'pinfo', [V1.scl_slope V1.scl_inter V1.vox_offset]',...
        'mat',   mat,...
        'n',     [n 1],...
        'descrip', V1.descrip,...
        'private',V1);
end