function W= kernel_ica(x)
m=size(x,1);
      W=kernel_ica_options(x,'contrasttype','oneunit','ncomp',m, ...
         'W0',rand_orth(m),'contrast','kgv','kernel','hermite','sig',1.5,'kap',.0001, ...
         'p',3,'polish',1,'restarts',4,'disp',0);
      W=kernel_ica_options(x,'W0',W,'contrast','kgv','kernel','gaussian','sig',.5,'kap',.001, ...
         'p',4,'polish',0,'restarts',1,'disp',0);
